# Internacionalizacao

# Pasta com as traducoes
arb-dir: lib/l10n

# Arquivo do idioma padrao
template-arb-file: app_en.arb

# Arquivo compilado gerado, que sera importado no seu programa, para acessar as strings
output-localization-file: app_localizations.dart