// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqH-krTo-pq2zugmXBu0P6gXa1aCqD8bw',
    appId: '1:764648321125:web:005ea5989dd807b0ba168c',
    messagingSenderId: '764648321125',
    projectId: 'fir-2024-3f602',
    authDomain: 'fir-2024-3f602.firebaseapp.com',
    storageBucket: 'fir-2024-3f602.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFoWVB6yxqLEFkyJPc1K_UBuITR4QoIkk',
    appId: '1:764648321125:android:f6fff9cbc6420ee4ba168c',
    messagingSenderId: '764648321125',
    projectId: 'fir-2024-3f602',
    storageBucket: 'fir-2024-3f602.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgwAfpESB7U2kUowYOBVBeRFnFRkrz73U',
    appId: '1:764648321125:ios:8819505ee78b2603ba168c',
    messagingSenderId: '764648321125',
    projectId: 'fir-2024-3f602',
    storageBucket: 'fir-2024-3f602.appspot.com',
    iosBundleId: 'br.edu.ufersa.app1201Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgwAfpESB7U2kUowYOBVBeRFnFRkrz73U',
    appId: '1:764648321125:ios:8819505ee78b2603ba168c',
    messagingSenderId: '764648321125',
    projectId: 'fir-2024-3f602',
    storageBucket: 'fir-2024-3f602.appspot.com',
    iosBundleId: 'br.edu.ufersa.app1201Firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqH-krTo-pq2zugmXBu0P6gXa1aCqD8bw',
    appId: '1:764648321125:web:9bdb6b46f125611eba168c',
    messagingSenderId: '764648321125',
    projectId: 'fir-2024-3f602',
    authDomain: 'fir-2024-3f602.firebaseapp.com',
    storageBucket: 'fir-2024-3f602.appspot.com',
  );
}
