// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDBo1FHyr7on1clqmqbtdWcCXys0LC0PA',
    appId: '1:171192914315:web:a0d42825f81a8b60245f8e',
    messagingSenderId: '171192914315',
    projectId: 'flutter2023-132c8',
    authDomain: 'flutter2023-132c8.firebaseapp.com',
    storageBucket: 'flutter2023-132c8.appspot.com',
    measurementId: 'G-QK7HB0SEWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2zRf5o5Yu1p_xaSwkIVSQGS1tpIl9Br4',
    appId: '1:171192914315:android:5019d68a43ddc910245f8e',
    messagingSenderId: '171192914315',
    projectId: 'flutter2023-132c8',
    storageBucket: 'flutter2023-132c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATtOG74v6qEhuL-tkL0QmdCVIIHuJ3W1w',
    appId: '1:171192914315:ios:cbaf44f670b974c4245f8e',
    messagingSenderId: '171192914315',
    projectId: 'flutter2023-132c8',
    storageBucket: 'flutter2023-132c8.appspot.com',
    iosClientId: '171192914315-rhdatb9a0jnjnju5nffj32f83eku168v.apps.googleusercontent.com',
    iosBundleId: 'br.edu.ufersa.app1201Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATtOG74v6qEhuL-tkL0QmdCVIIHuJ3W1w',
    appId: '1:171192914315:ios:594b01f974bb2f67245f8e',
    messagingSenderId: '171192914315',
    projectId: 'flutter2023-132c8',
    storageBucket: 'flutter2023-132c8.appspot.com',
    iosClientId: '171192914315-g1vu5u9lotc4d78mj58avmgf428tr149.apps.googleusercontent.com',
    iosBundleId: 'br.edu.ufersa.app1201Firebase.RunnerTests',
  );
}
